import { Producto } from "./types";

export const CATALOG_DATA: Producto[] = [
  // Vidrio 3mm
  { codigo: "3MMC1.8",   categoria: "Vidrio 3mm", descripcion: "Cristal Claro",        dimensiones: "1.80 x 2.60m",   precio: 492,   stock: 2, unidad: "hoja" },
  { codigo: "3MME1.8",   categoria: "Vidrio 3mm", descripcion: "Espejo",               dimensiones: "1.80 x 2.60m",   precio: 860,   stock: 2, unidad: "hoja" },
  { codigo: "3MMF1.8",   categoria: "Vidrio 3mm", descripcion: "Filtrasol",            dimensiones: "1.80 x 2.60m",   precio: 930,   stock: 2, unidad: "hoja" },
  { codigo: "3MMP1.8",   categoria: "Vidrio 3mm", descripcion: "Pavia Satinado Claro", dimensiones: "1.80 x 2.60m",   precio: 1454,  stock: 2, unidad: "hoja" },
  { codigo: "76105",     categoria: "Vidrio 3mm", descripcion: "Sol Lite Claro",       dimensiones: "1.80 x 2.60m",   precio: 1350,  stock: 2, unidad: "hoja" },
  { codigo: "76106",     categoria: "Vidrio 3mm", descripcion: "Tintex",               dimensiones: "1.80 x 2.60m",   precio: 1200,  stock: 2, unidad: "hoja" },

  // Vidrio 4mm
  { codigo: "4MMC1.8",   categoria: "Vidrio 4mm", descripcion: "Cristal Claro",        dimensiones: "1.80 x 2.60m",   precio: 893,   stock: 2, unidad: "hoja" },
  { codigo: "76108",     categoria: "Vidrio 4mm", descripcion: "Cristal Claro",        dimensiones: "2.3m x 2.6m",    precio: 1480,  stock: 2, unidad: "hoja" },
  { codigo: "4MME1.8",   categoria: "Vidrio 4mm", descripcion: "Espejo",               dimensiones: "1.80 x 2.60m",   precio: 1526,  stock: 2, unidad: "hoja" },
  { codigo: "76110",     categoria: "Vidrio 4mm", descripcion: "Espejo",               dimensiones: "2.3m x 2.6m",    precio: 2350,  stock: 2, unidad: "hoja" },

  // Vidrio 6mm
  { codigo: "76111",     categoria: "Vidrio 6mm", descripcion: "Solarblue",            dimensiones: "2.60m x 3.60m",  precio: 4800,  stock: 2, unidad: "hoja" },
  { codigo: "6MMC1.8",   categoria: "Vidrio 6mm", descripcion: "Cristal Claro",        dimensiones: "1.80 x 2.60m",   precio: 985,   stock: 2, unidad: "hoja" },
  { codigo: "6MMC2.3",   categoria: "Vidrio 6mm", descripcion: "Cristal Claro",        dimensiones: "2.3m x 2.6m",    precio: 1258,  stock: 2, unidad: "hoja" },
  { codigo: "6MMC3",     categoria: "Vidrio 6mm", descripcion: "Cristal Claro",        dimensiones: "2.60m x 3.0m",   precio: 1642,  stock: 2, unidad: "hoja" },
  { codigo: "6MMC3.6",   categoria: "Vidrio 6mm", descripcion: "Cristal Claro",        dimensiones: "2.60m x 3.60m",  precio: 3750,  stock: 2, unidad: "hoja" },
  { codigo: "6MME1.8",   categoria: "Vidrio 6mm", descripcion: "Espejo",               dimensiones: "1.80 x 2.60m",   precio: 2016,  stock: 2, unidad: "hoja" },
  { codigo: "6MME2.3",   categoria: "Vidrio 6mm", descripcion: "Espejo",               dimensiones: "2.3m x 2.6m",    precio: 2576,  stock: 2, unidad: "hoja" },
  { codigo: "6MME3.6",   categoria: "Vidrio 6mm", descripcion: "Espejo",               dimensiones: "2.60m x 3.60m",  precio: 4032,  stock: 2, unidad: "hoja" },
  { codigo: "76119",     categoria: "Vidrio 6mm", descripcion: "Espejo Filtrasol",     dimensiones: "1.80 x 2.60m",   precio: 3150,  stock: 2, unidad: "hoja" },
  { codigo: "6MMEV3.6",  categoria: "Vidrio 6mm", descripcion: "Espejo Vitrosol",      dimensiones: "2.60m x 3.60m",  precio: 6935,  stock: 2, unidad: "hoja" },
  { codigo: "76121",     categoria: "Vidrio 6mm", descripcion: "Espejo Bronce",        dimensiones: "3.21m x 2.55m",  precio: 5900,  stock: 2, unidad: "hoja" },
  { codigo: "6MMF1.8",   categoria: "Vidrio 6mm", descripcion: "Filtrasol",            dimensiones: "1.80 x 2.60m",   precio: 1195,  stock: 2, unidad: "hoja" },
  { codigo: "6MMF2.3",   categoria: "Vidrio 6mm", descripcion: "Filtrasol",            dimensiones: "2.3m x 2.6m",    precio: 1527,  stock: 2, unidad: "hoja" },
  { codigo: "6MMF3",     categoria: "Vidrio 6mm", descripcion: "Filtrasol",            dimensiones: "2.60m x 3.0m",   precio: 1991,  stock: 2, unidad: "hoja" },
  { codigo: "6MMF3.6",   categoria: "Vidrio 6mm", descripcion: "Filtrasol",            dimensiones: "2.60m x 3.60m",  precio: 2390,  stock: 2, unidad: "hoja" },
  { codigo: "76126",     categoria: "Vidrio 6mm", descripcion: "Pavia Claro",          dimensiones: "1.80 x 2.60m",   precio: 3400,  stock: 2, unidad: "hoja" },
  { codigo: "76127",     categoria: "Vidrio 6mm", descripcion: "SQL Lite Claro",       dimensiones: "1.80 x 2.60m",   precio: 2800,  stock: 2, unidad: "hoja" },
  { codigo: "6MMT1.8",   categoria: "Vidrio 6mm", descripcion: "Tintex",               dimensiones: "1.80 x 2.60m",   precio: 1310,  stock: 2, unidad: "hoja" },
  { codigo: "6MMT2.3",   categoria: "Vidrio 6mm", descripcion: "Tintex",               dimensiones: "2.3m x 2.6m",    precio: 1675,  stock: 2, unidad: "hoja" },
  { codigo: "6MMT3.6",   categoria: "Vidrio 6mm", descripcion: "Tintex",               dimensiones: "2.60m x 3.60m",  precio: 2621,  stock: 2, unidad: "hoja" },
  { codigo: "76131",     categoria: "Vidrio 6mm", descripcion: "Tintex Plus",          dimensiones: "1.80 x 2.60m",   precio: 2750,  stock: 2, unidad: "hoja" },
  { codigo: "76132",     categoria: "Vidrio 6mm", descripcion: "Tintex Plus",          dimensiones: "2.60m x 3.60m",  precio: 5600,  stock: 2, unidad: "hoja" },
  { codigo: "6MMV3.6",   categoria: "Vidrio 6mm", descripcion: "Vitrosol",             dimensiones: "2.60m x 3.60m",  precio: 4184,  stock: 2, unidad: "hoja" },
  { codigo: "76134",     categoria: "Vidrio 6mm", descripcion: "Reflecta Azul",        dimensiones: "1.80 x 2.50m",   precio: 4100,  stock: 2, unidad: "hoja" },
  { codigo: "76135",     categoria: "Vidrio 6mm", descripcion: "Reflecta Azul",        dimensiones: "2.5m x 3.6m",    precio: 8200,  stock: 2, unidad: "hoja" },
  { codigo: "76136",     categoria: "Vidrio 6mm", descripcion: "Reflecta Bronce",      dimensiones: "1.80 x 2.50m",   precio: 3980,  stock: 2, unidad: "hoja" },
  { codigo: "RB3.6",     categoria: "Vidrio 6mm", descripcion: "Reflecta Bronce",      dimensiones: "3.6m x 2.5m",    precio: 5087,  stock: 2, unidad: "hoja" },
  { codigo: "RP3.6",     categoria: "Vidrio 6mm", descripcion: "Reflecta Plata",       dimensiones: "3.6m x 2.5m",    precio: 4891,  stock: 2, unidad: "hoja" },

  // Vidrio 9mm
  { codigo: "9MMC3.60",  categoria: "Vidrio 9mm", descripcion: "Cristal Claro",        dimensiones: "2.60m x 3.60m",  precio: 3670,  stock: 2, unidad: "hoja" },
  { codigo: "9MMF3.6",   categoria: "Vidrio 9mm", descripcion: "Filtrasol",            dimensiones: "2.60m x 3.60m",  precio: 5210,  stock: 2, unidad: "hoja" },
  { codigo: "9MMT3.6",   categoria: "Vidrio 9mm", descripcion: "Tintex",               dimensiones: "2.60m x 3.60m",  precio: 5395,  stock: 2, unidad: "hoja" },
  { codigo: "9MMV3.6",   categoria: "Vidrio 9mm", descripcion: "Vitrosol",             dimensiones: "2.60m x 3.60m",  precio: 11087, stock: 2, unidad: "hoja" },

  // Perfil aluminio 3"
  { codigo: "7826",      categoria: "Perfil aluminio 3\"", descripcion: "Jamba Sencilla ó chambrana",  dimensiones: "3\"", precio: 458,  stock: 2, unidad: "pieza" },
  { codigo: "17862",     categoria: "Perfil aluminio 3\"", descripcion: "Jamba c/ mosq.",              dimensiones: "3\"", precio: 750,  stock: 2, unidad: "pieza" },
  { codigo: "9957N",     categoria: "Perfil aluminio 3\"", descripcion: "Riel sencillo",               dimensiones: "3\"", precio: 439,  stock: 2, unidad: "pieza" },
  { codigo: "9272",      categoria: "Perfil aluminio 3\"", descripcion: "Riel c/ mosq.",               dimensiones: "3\"", precio: 467,  stock: 2, unidad: "pieza" },
  { codigo: "7842",      categoria: "Perfil aluminio 3\"", descripcion: "Zoclo puerta 2 Venas alto",   dimensiones: "3\"", precio: 574,  stock: 2, unidad: "pieza" },
  { codigo: "7835",      categoria: "Perfil aluminio 3\"", descripcion: "Zoclo ventana 1 Vena",        dimensiones: "3\"", precio: 374,  stock: 2, unidad: "pieza" },
  { codigo: "7836",      categoria: "Perfil aluminio 3\"", descripcion: "Zoclo cabezal",               dimensiones: "3\"", precio: 214,  stock: 2, unidad: "pieza" },
  { codigo: "9082",      categoria: "Perfil aluminio 3\"", descripcion: "Intermedio",                  dimensiones: "3\"", precio: 228,  stock: 2, unidad: "pieza" },
  { codigo: "7847",      categoria: "Perfil aluminio 3\"", descripcion: "Cerco chapa",                 dimensiones: "3\"", precio: 303,  stock: 2, unidad: "pieza" },
  { codigo: "9135",      categoria: "Perfil aluminio 3\"", descripcion: "Bolsa",                       dimensiones: "3\"", precio: 437,  stock: 2, unidad: "pieza" },
  { codigo: "9136",      categoria: "Perfil aluminio 3\"", descripcion: "Escalonado",                  dimensiones: "3\"", precio: 396,  stock: 2, unidad: "pieza" },
  { codigo: "7315",      categoria: "Perfil aluminio 3\"", descripcion: "Tapa bolsa",                  dimensiones: "3\"", precio: 236,  stock: 2, unidad: "pieza" },
  { codigo: "7316",      categoria: "Perfil aluminio 3\"", descripcion: "Tapa lisa",                   dimensiones: "3\"", precio: 168,  stock: 2, unidad: "pieza" },
  { codigo: "10237",     categoria: "Perfil aluminio 3\"", descripcion: "Tapa bolsa corta",            dimensiones: "3\"", precio: 236,  stock: 2, unidad: "pieza" },
  { codigo: "9112",      categoria: "Perfil aluminio 3\"", descripcion: "Jonquillo",                   dimensiones: "3\"", precio: 150,  stock: 2, unidad: "pieza" },
  { codigo: "9114",      categoria: "Perfil aluminio 3\"", descripcion: "Bolsa lisa ó canal liso",     dimensiones: "3\"", precio: 409,  stock: 2, unidad: "pieza" },
  { codigo: "9115",      categoria: "Perfil aluminio 3\"", descripcion: "Esquinero",                   dimensiones: "3\"", precio: 667,  stock: 2, unidad: "pieza" },
  { codigo: "10235",     categoria: "Perfil aluminio 3\"", descripcion: "Bolsa corta ó rolar",         dimensiones: "3\"", precio: 566,  stock: 2, unidad: "pieza" },
  { codigo: "10266",     categoria: "Perfil aluminio 3\"", descripcion: "Moldura Unión",               dimensiones: "3\"", precio: 275,  stock: 2, unidad: "pieza" },

  // Perfil aluminio 2"
  { codigo: "7518",      categoria: "Perfil aluminio 2\"", descripcion: "Jamba sencilla",              dimensiones: "2\"", precio: 400,  stock: 2, unidad: "pieza" },
  { codigo: "7819",      categoria: "Perfil aluminio 2\"", descripcion: "Jamba c/ mosqu.",             dimensiones: "2\"", precio: 600,  stock: 2, unidad: "pieza" },
  { codigo: "9953",      categoria: "Perfil aluminio 2\"", descripcion: "Riel",                        dimensiones: "2\"", precio: 290,  stock: 2, unidad: "pieza" },
  { codigo: "8370",      categoria: "Perfil aluminio 2\"", descripcion: "Riel c/ mosq.",               dimensiones: "2\"", precio: 400,  stock: 2, unidad: "pieza" },
  { codigo: "7821",      categoria: "Perfil aluminio 2\"", descripcion: "Cerco chapa puerta",          dimensiones: "2\"", precio: 220,  stock: 2, unidad: "pieza" },
  { codigo: "9955",      categoria: "Perfil aluminio 2\"", descripcion: "Traslape",                    dimensiones: "2\"", precio: 270,  stock: 2, unidad: "pieza" },
  { codigo: "11837",     categoria: "Perfil aluminio 2\"", descripcion: "Zoclo cabezal",               dimensiones: "2\"", precio: 190,  stock: 2, unidad: "pieza" },
  { codigo: "7825",      categoria: "Perfil aluminio 2\"", descripcion: "Zoclo puerta alto",           dimensiones: "2\"", precio: 471,  stock: 2, unidad: "pieza" },
  { codigo: "9083",      categoria: "Perfil aluminio 2\"", descripcion: "Bolsa",                       dimensiones: "2\"", precio: 390,  stock: 2, unidad: "pieza" },
  { codigo: "9084",      categoria: "Perfil aluminio 2\"", descripcion: "Escalonado",                  dimensiones: "2\"", precio: 300,  stock: 2, unidad: "pieza" },
  { codigo: "9085",      categoria: "Perfil aluminio 2\"", descripcion: "Tapa bolsa",                  dimensiones: "2\"", precio: 200,  stock: 2, unidad: "pieza" },
  { codigo: "9088",      categoria: "Perfil aluminio 2\"", descripcion: "Junquillo",                   dimensiones: "2\"", precio: 120,  stock: 2, unidad: "pieza" },
  { codigo: "2341",      categoria: "Perfil aluminio 2\"", descripcion: "Tapa lisa",                   dimensiones: "2\"", precio: 150,  stock: 2, unidad: "pieza" },
  { codigo: "8586",      categoria: "Perfil aluminio 2\"", descripcion: "Esquinero",                   dimensiones: "2\"", precio: 560,  stock: 2, unidad: "pieza" },
  { codigo: "8591",      categoria: "Perfil aluminio 2\"", descripcion: "Bolsa lisa o canal lisa",     dimensiones: "2\"", precio: 350,  stock: 2, unidad: "pieza" },
  { codigo: "7818N",     categoria: "Perfil aluminio 2\"", descripcion: "Adaptador OXXO de 2\" a 6.10 mts", dimensiones: "2\"", precio: 187, stock: 2, unidad: "pieza" },

  // Accesorios
  { codigo: "SAC6B30",   categoria: "Accesorios", descripcion: "Sellador Acrílico Blanco",                       dimensiones: "", precio: 35,  stock: 2, unidad: "pieza" },
  { codigo: "CH41231T",  categoria: "Accesorios", descripcion: "Chapa de Perico Tetra #4123 Natural",            dimensiones: "", precio: 169, stock: 2, unidad: "pieza" },
  { codigo: "JE31",      categoria: "Accesorios", descripcion: "Jaladera de Embutir p/Puerta Natural",           dimensiones: "", precio: 37,  stock: 2, unidad: "pieza" },
  { codigo: "2145000GR", categoria: "Accesorios", descripcion: "Jaladera Tirador Coahuila Iny 20cm Gris",        dimensiones: "", precio: 77,  stock: 2, unidad: "pieza" },
  { codigo: "CD70T",     categoria: "Accesorios", descripcion: "Carretilla S70/100 Eurovent Doble Tándem",       dimensiones: "", precio: 115, stock: 2, unidad: "pieza" },
];
